ALTER TABLE "farms" ADD COLUMN "farm_code" text;--> statement-breakpoint
ALTER TABLE "farms" ADD COLUMN "department" text;--> statement-breakpoint
ALTER TABLE "farms" ADD COLUMN "municipality" text;--> statement-breakpoint
ALTER TABLE "farms" ADD COLUMN "previous_total_production_qq" numeric;--> statement-breakpoint
ALTER TABLE "farms" ADD COLUMN "production_data_year" integer;--> statement-breakpoint
ALTER TABLE "farms" ADD COLUMN "water_source" text;--> statement-breakpoint
ALTER TABLE "farms" ADD COLUMN "road_access" text;--> statement-breakpoint
ALTER TABLE "farms" ADD COLUMN "shade_trees" text;--> statement-breakpoint
ALTER TABLE "lots" ADD COLUMN "descriptive_name" text;--> statement-breakpoint
ALTER TABLE "lots" ADD COLUMN "varieties_composition" jsonb;--> statement-breakpoint
ALTER TABLE "lots" ADD COLUMN "processing_method" text;--> statement-breakpoint
ALTER TABLE "lots" ADD COLUMN "average_plant_age_years" integer;--> statement-breakpoint
ALTER TABLE "lots" ADD COLUMN "renovation_in_progress" boolean;--> statement-breakpoint
ALTER TABLE "lots" ADD COLUMN "new_variety" text;--> statement-breakpoint
ALTER TABLE "lots" ADD COLUMN "renovation_percent" numeric;--> statement-breakpoint
ALTER TABLE "lots" ADD COLUMN "renovation_start_year" integer;--> statement-breakpoint
ALTER TABLE "lots" ADD COLUMN "management_type" text;--> statement-breakpoint
ALTER TABLE "lots" ADD COLUMN "previous_production_qq" numeric;--> statement-breakpoint
ALTER TABLE "lots" ADD COLUMN "production_data_year" integer;--> statement-breakpoint
ALTER TABLE "lots" ADD COLUMN "rust_last_cycle" text;--> statement-breakpoint
ALTER TABLE "lots" ADD COLUMN "borer_last_cycle" text;--> statement-breakpoint
ALTER TABLE "lots" ADD COLUMN "fertilized_last_cycle" boolean;--> statement-breakpoint
ALTER TABLE "lots" ADD COLUMN "available_for_coinvestment" boolean;--> statement-breakpoint
ALTER TABLE "lots" ADD COLUMN "accepts_split_6040" boolean;--> statement-breakpoint
ALTER TABLE "lots" ADD COLUMN "minimum_price_cents_per_lb" integer;--> statement-breakpoint
ALTER TABLE "lots" ADD COLUMN "lot_observations" text;--> statement-breakpoint
CREATE INDEX "farms_farm_code_idx" ON "farms" USING btree ("farm_code");